likelion-backend-2nd-project-team11/book-more

- backend/src/main/java/site/bookmore/bookmoreserver/users/entity/Role.java
- backend/src/main/java/site/bookmore/bookmoreserver/users/entity/Tier.java
- backend/src/main/java/site/bookmore/bookmoreserver/users/entity/User.java
- backend/src/main/java/site/bookmore/bookmoreserver/users/repositroy/UserRepository.java
User Entity, UserRepository, Role, Tier Enum
> User Entity, UserRepository, Role, Tier Enum

- backend/src/main/java/site/bookmore/bookmoreserver/books/entity/Author.java
- backend/src/main/java/site/bookmore/bookmoreserver/books/entity/Book.java
- backend/src/main/java/site/bookmore/bookmoreserver/books/entity/Translator.java
- backend/src/main/java/site/bookmore/bookmoreserver/books/repository/BookRepository.java
> [Feat] Book 엔티티 작성

- backend/src/main/java/site/bookmore/bookmoreserver/users/entity/Role.java
- backend/src/main/java/site/bookmore/bookmoreserver/users/entity/Tier.java
- backend/src/main/java/site/bookmore/bookmoreserver/users/entity/User.java
- backend/src/main/java/site/bookmore/bookmoreserver/users/repositroy/UserRepository.java
- User
- Role
- Tier
- UserRepository 작성
> [Feat] User 엔티티 작성

- backend/src/main/java/site/bookmore/bookmoreserver/common/entity/BaseEntity.java
- backend/src/main/java/site/bookmore/bookmoreserver/common/exception/ErrorCode.java
- backend/src/main/java/site/bookmore/bookmoreserver/config/AuditingConfig.java
- BaseEntity
- ErrorCode
- AuditingConfig
> [Feat] 도메인 공통 분모 구현

- backend/src/main/java/site/bookmore/bookmoreserver/books/entity/Book.java
> [Fix] 컬럼명 수정

- backend/src/main/java/site/bookmore/bookmoreserver/common/dto/ErrorResponse.java
- backend/src/main/java/site/bookmore/bookmoreserver/common/dto/ResultResponse.java
- backend/src/main/java/site/bookmore/bookmoreserver/common/exception/AbstractAppException.java
- backend/src/main/java/site/bookmore/bookmoreserver/common/exception/ErrorCode.java
- backend/src/main/java/site/bookmore/bookmoreserver/common/exception/conflict/DuplicateEmailException.java
- backend/src/main/java/site/bookmore/bookmoreserver/common/exception/conflict/DuplicateNicknameException.java
- backend/src/main/java/site/bookmore/bookmoreserver/common/exception/forbidden/InvalidPermissionException.java
- backend/src/main/java/site/bookmore/bookmoreserver/common/exception/internal_server_error/DatabaseException.java
- backend/src/main/java/site/bookmore/bookmoreserver/common/exception/not_found/BookNotFoundException.java
- backend/src/main/java/site/bookmore/bookmoreserver/common/exception/not_found/EmailNotFoundException.java
- backend/src/main/java/site/bookmore/bookmoreserver/common/exception/not_found/ReviewNotFoundException.java
- backend/src/main/java/site/bookmore/bookmoreserver/common/exception/not_found/UserNotFoundException.java
- backend/src/main/java/site/bookmore/bookmoreserver/common/exception/request_timeout/APIRequestTimeoutException.java
- backend/src/main/java/site/bookmore/bookmoreserver/common/exception/unauthorized/InvalidPasswordException.java
- backend/src/main/java/site/bookmore/bookmoreserver/common/exception/unauthorized/InvalidTokenException.java
- backend/src/main/java/site/bookmore/bookmoreserver/common/exception/unauthorized/UserNotLoggedInException.java
- backend/src/main/java/site/bookmore/bookmoreserver/security/config/WebSecurityConfig.java
- backend/src/main/java/site/bookmore/bookmoreserver/security/entrypoint/CustomAccessDeniedEntryPoint.java
- backend/src/main/java/site/bookmore/bookmoreserver/security/entrypoint/CustomAuthenticationEntryPoint.java
- [Feat] Security 설정
- [Feat] EntryPoint 추가
- [Feat] ResultResponse, ErrorResponse 추가
> [Feat] 공통사항 추가

- backend/src/main/java/site/bookmore/bookmore/security/config/WebSecurityConfig.java
- Request URI 제한 설정 에러로 인해 실행 불가
> [Hotfix] 시큐리티 설정 변경

- backend/src/main/java/site/bookmore/bookmore/alarms/controller/AlarmController.java
- backend/src/main/java/site/bookmore/bookmore/alarms/entity/Alarm.java
- backend/src/main/java/site/bookmore/bookmore/alarms/entity/AlarmType.java
- backend/src/main/java/site/bookmore/bookmore/alarms/entity/dto/AlarmResponse.java
- backend/src/main/java/site/bookmore/bookmore/alarms/repository/AlarmRepository.java
- backend/src/main/java/site/bookmore/bookmore/alarms/service/AlarmService.java
- backend/src/main/java/site/bookmore/bookmore/observer/event/alarm/AlarmCreate.java
- backend/src/main/java/site/bookmore/bookmore/observer/handler/AlarmEventHandler.java
- backend/src/main/java/site/bookmore/bookmore/security/config/AsyncConfig.java
- backend/src/test/java/site/bookmore/bookmore/alarms/controller/AlarmControllerTest.java
알림 기능 구현
- 알림 구현
- event handler 구현
> 알람 이벤트 핸들러 구현

- backend/src/main/java/site/bookmore/bookmore/common/entity/BaseEntity.java
- backend/src/main/java/site/bookmore/bookmore/common/exception/ErrorCode.java
- backend/src/main/java/site/bookmore/bookmore/common/exception/bad_request/FollowNotMeException.java
- backend/src/main/java/site/bookmore/bookmore/common/exception/not_found/FollowNotFoundException.java
- backend/src/main/java/site/bookmore/bookmore/users/controller/FollowController.java
- backend/src/main/java/site/bookmore/bookmore/users/dto/FollowerResponse.java
- backend/src/main/java/site/bookmore/bookmore/users/dto/FollowingResponse.java
- backend/src/main/java/site/bookmore/bookmore/users/entity/Follow.java
- backend/src/main/java/site/bookmore/bookmore/users/repositroy/FollowRepository.java
- backend/src/main/java/site/bookmore/bookmore/users/service/FollowService.java
- backend/src/test/java/site/bookmore/bookmore/users/controller/FollowControllerTest.java
- backend/src/test/java/site/bookmore/bookmore/users/service/FollowServiceTest.java
팔로우 기능 구현
1. 팔로우 기능
2. 언팔로우 기능
3. 팔로잉 조회
4. 팔로워 조회
- 팔로우 했을 때 deletedDatetime =null
- 언팔로우 했을 때 deletedDatetime=언팔한 시간
> 팔로우/팔로잉 기능 구현

- backend/src/main/java/site/bookmore/bookmore/common/exception/GlobalExceptionHandler.java
GlobalExceptionHandler 구현
- AbstractAppException 처리
- PersistenceException (DB에러) 처리
> GlobalExceptionHandler 구현

- backend/src/main/java/site/bookmore/bookmore/users/service/FollowService.java
> 팔로우 알람 기능 구현

- frontend/css/header.css
- frontend/css/home.css
- frontend/html/header.html
- frontend/html/home.html
- frontend/js/header.js
- frontend/js/home.js
home, header (html,css,js)
- home, header 양식
> [Feat] home, header

- backend/src/main/java/site/bookmore/bookmore/users/controller/UserController.java
- backend/src/main/java/site/bookmore/bookmore/users/dto/UserResponse.java
- backend/src/main/java/site/bookmore/bookmore/users/dto/UserUpdateRequest.java
- backend/src/main/java/site/bookmore/bookmore/users/dto/UserUpdateResponse.java
- backend/src/main/java/site/bookmore/bookmore/users/entity/User.java
- backend/src/main/java/site/bookmore/bookmore/users/repositroy/UserRepository.java
- backend/src/main/java/site/bookmore/bookmore/users/service/UserService.java
- backend/src/test/java/site/bookmore/bookmore/users/controller/UserControllerTest.java
- backend/src/test/java/site/bookmore/bookmore/users/service/UserServiceTest.java
회원 정보 수정/ 회원 탈퇴 구현
- 회원 정보 수정
- 회원 탈퇴
> 회원 정보 수정/ 회원 탈퇴 기능

- backend/src/main/java/site/bookmore/bookmore/config/WebMvcConfig.java
- backend/src/main/java/site/bookmore/bookmore/security/config/WebSecurityConfig.java
시큐리티 접근 제한 설정
- 시큐리티 접근 제한 URI 설정
> [Feat] 시큐리티 접근 제한 설정

- backend/src/main/java/site/bookmore/bookmore/books/controller/ReviewController.java
- backend/src/main/java/site/bookmore/bookmore/books/dto/ReviewPageResponse.java
- backend/src/main/java/site/bookmore/bookmore/books/dto/ReviewRequest.java
- backend/src/main/java/site/bookmore/bookmore/books/entity/Chart.java
- backend/src/main/java/site/bookmore/bookmore/books/entity/Review.java
- backend/src/main/java/site/bookmore/bookmore/books/repository/ReviewRepository.java
- backend/src/main/java/site/bookmore/bookmore/books/service/ReviewService.java
- backend/src/test/java/site/bookmore/bookmore/books/controller/ReviewControllerTest.java
- backend/src/test/java/site/bookmore/bookmore/books/service/ReviewServiceTest.java
도서 리뷰 수정 기능 구현
도서 리뷰 삭제 기능 구현
- 리뷰 작성자에 한해, 리뷰 id로 조회하여 리뷰가 수정/삭제되도록 기능을 구현했습니다.
> 도서 리뷰 수정/삭제 기능 구현

- backend/src/main/java/site/bookmore/bookmore/common/dto/ResultResponse.java
- backend/src/main/java/site/bookmore/bookmore/common/exception/GlobalExceptionHandler.java
- backend/src/main/java/site/bookmore/bookmore/users/controller/UserController.java
- backend/src/main/java/site/bookmore/bookmore/users/dto/UserJoinRequest.java
- backend/src/main/java/site/bookmore/bookmore/users/dto/UserLoginRequest.java
- backend/src/test/java/site/bookmore/bookmore/users/controller/UserControllerTest.java
이메일 형식에 맞게 회원 가입 및 로그인 처리
- join, login requset 에 email 어노테이션 추가
- GlobalHandler 에 예외 처리 추가
- Contoroller Join, Login 파라미터 @Valid 추가
> 이메일 형식 로직 추가

- backend/src/main/java/site/bookmore/bookmore/books/repository/ReviewRepository.java
- backend/src/main/java/site/bookmore/bookmore/books/service/ReviewService.java
- backend/src/test/java/site/bookmore/bookmore/books/service/ReviewServiceTest.java
리뷰 삭제 시 좋아요 | 취소 / 리뷰 수정 / 리뷰 삭제가 되지 않도록 수정
- 리뷰 삭제 기능을 가장 마지막에 만드는 바람에 이전에 만든 모든 기능에서 삭제되었는지를 제대로 체크하고 있지 않아서 수정을 했습니다.
- [x ] 테스트 코드 작성 및 통과
> 리뷰 삭제 체크 수정

- .github/workflows/front.yml
- FrontEnd CI PipeLine 작성
- 프론트엔드 workflow 작성했습니다.
- secret 변수 등록 해줘야 합니다.
> FrontEnd CI PipeLine 작성

- frontend/css/detail.css
- frontend/detail.html
- Detail 프론트 페이지 작성
- Detail 페이지의 팔로우/팔로잉 프론트 페이지 작성
> Detail 페이지 작성

- frontend/css/join-login.css
- frontend/join.html
- frontend/js/join.js
- frontend/js/login.js
- frontend/login.html
- 회원가입 로그인 프론트 구현
-  회원가입 로그인 프론트 구현
-  유효성 검사 부분 때문에 자바 스크립트가 돌지 않아서 뺏습니다.
-  폰트때문에 비밀번호 블러 처리가 안되서 body 부분은 폰트를 뺏습니다.
> 로그인 회원가입 프론트 구현

- frontend/book.html
- frontend/books.html
- frontend/css/index.css
- frontend/css/nav.css
- frontend/index.html
- frontend/js/bookSearch.js
- frontend/top-bar.html
도서 검색, 상세 조회 페이지 수정
- 네비게이션 바 수정.
- 검색창에서 엔터 누를시 검색되도록 추가.
> 도서 검색, 상세조회 페이지 수정

- .github/workflows/develop.yml
- .github/workflows/front.yml
- .github/workflows/main.yml
- workflow 수정
- develop.yml 파일 브랜치 develop/backend로 수정
- main.yml 파일  ADD coverage to PR에 if 문 추가
- front.yml 파일 브랜치 main으로 수정
> workflow 수정

- backend/src/main/java/site/bookmore/bookmore/challenge/controller/ChallengeController.java
- backend/src/main/java/site/bookmore/bookmore/challenge/dto/ChallengeRequest.java
- backend/src/main/java/site/bookmore/bookmore/challenge/entity/Challenge.java
- backend/src/main/java/site/bookmore/bookmore/challenge/repository/ChallengeRepository.java
- backend/src/main/java/site/bookmore/bookmore/challenge/service/ChallengeService.java
수정
- controller, service, repository, request 수정
> [update] controller, request, repository, service

- backend/build.gradle
- backend/src/main/java/site/bookmore/bookmore/alarms/controller/AlarmController.java
- backend/src/main/java/site/bookmore/bookmore/books/controller/BookController.java
- backend/src/main/java/site/bookmore/bookmore/books/controller/ReviewController.java
- backend/src/main/java/site/bookmore/bookmore/challenge/controller/ChallengeController.java
- backend/src/main/java/site/bookmore/bookmore/common/dto/Paging.java
- backend/src/main/java/site/bookmore/bookmore/common/support/annotation/Authorized.java
- backend/src/main/java/site/bookmore/bookmore/config/SwaggerConfig.java
- backend/src/main/java/site/bookmore/bookmore/users/controller/FollowController.java
- backend/src/main/java/site/bookmore/bookmore/users/controller/UserController.java
Swagger 설정
- 스웨거 추가하였습니다.
- 권한이 필요한 메소드에는 `@Authorized` 어노테이션을 붙여두었습니다.
- 이후에 추가되는 기능이 추가되면 Swagger도 설정해주세요.
> Swagger 설정

- backend/src/main/java/site/bookmore/bookmore/users/repositroy/RanksRepository.java
- backend/src/main/java/site/bookmore/bookmore/users/service/UserService.java
- backend/src/test/java/site/bookmore/bookmore/users/service/UserServiceTest.java
> [Hotfix] 첫 유저 회원가입 시 NPE 발생 수정

- backend/src/main/java/site/bookmore/bookmore/books/dto/BookSearchParams.java
- backend/src/main/java/site/bookmore/bookmore/books/entity/Author.java
- backend/src/main/java/site/bookmore/bookmore/books/entity/Book.java
- backend/src/main/java/site/bookmore/bookmore/books/entity/Translator.java
- backend/src/main/java/site/bookmore/bookmore/books/util/mapper/BookMapper.java
- backend/src/main/java/site/bookmore/bookmore/common/exception/GlobalExceptionHandler.java
> [Hotfix] Book cached Null 및 Author, Translator 매핑 이슈

- backend/src/main/java/site/bookmore/bookmore/users/dto/RanksResponse.java
- backend/src/main/java/site/bookmore/bookmore/users/entity/Ranks.java
- backend/src/main/java/site/bookmore/bookmore/users/service/RanksService.java
- backend/src/main/java/site/bookmore/bookmore/users/service/UserService.java
- backend/src/main/java/site/bookmore/bookmore/users/vo/RanksNativeVo.java
nickname 추가
- ranks 테이블에 nickName을 추가하였습니다.
> Feature/#42 ranks 테이블에 nickname 추가

- frontend/css/mypage.css
- frontend/mypage.html
> [feat] mypage.html/css

- backend/src/main/java/site/bookmore/bookmore/users/controller/UserController.java
- backend/src/main/java/site/bookmore/bookmore/users/dto/UserDetailResponse.java
- backend/src/main/java/site/bookmore/bookmore/users/service/UserService.java
- 유저 상세 조회 추가
- 유저 상세 조회 추가
- 닉네임, 팔로잉수, 팔로워수 출력
> 유저 상세 조회 추가

- frontend/notifications/notifications.html
> 알림 페이지 구현(디자인)

- frontend/css/detail.css
- frontend/ranks.html
> Feature/#133 ranks 페이지

- frontend/js/constant.js
> Base URL 수정

- .github/workflows/front.yml
- front.yml에 images 파일을 제외하는 exclude 옵션 추가
> front.yml exclude 옵션 추가

- backend/src/main/java/site/bookmore/bookmore/books/entity/Book.java
- backend/src/main/java/site/bookmore/bookmore/books/util/api/naver/dto/Item.java
- backend/src/main/java/site/bookmore/bookmore/books/util/mapper/BookMapper.java
- backend/src/test/java/site/bookmore/bookmore/books/util/api/naver/dto/ItemTest.java
Book introduce 컬럼 길이 수정
- 2000자로 제한 증가.
- 2000자가 넘는 데이터가 들어왔을때 후처리 로직 추가
- DB 업데이트 필요합니다.
> Book introduce 컬럼 길이 수정

- backend/src/main/java/site/bookmore/bookmore/books/service/ReviewService.java
- backend/src/main/java/site/bookmore/bookmore/observer/event/alarm/AlarmListCreate.java
- backend/src/main/java/site/bookmore/bookmore/observer/handler/AlarmEventHandler.java
- 팔로잉이 리뷰를 등록했을 때의 알림 로직 변경
- 알람 스레드 한 개만 생성되게 로직 변경
> Feature/#138 팔로잉이 리뷰를 등록했을 때의 알림 로직 변경

- Weekly_Log/[3주차]idea_11팀_진행상황_공유.md
> Weekly_Log 3주차

- backend/src/main/java/site/bookmore/bookmore/books/repository/ReviewRepository.java
- backend/src/main/java/site/bookmore/bookmore/books/service/ReviewService.java
- backend/src/main/java/site/bookmore/bookmore/users/controller/UserController.java
- backend/src/test/java/site/bookmore/bookmore/users/controller/UserControllerTest.java
유저 id로 리뷰 조회하는 기능
- 마이 피드, 유저 피드를 보여주기 위한 유저 id로 리뷰 조회하는 기능을 추가하였습니다.
> 유저 id로 리뷰 조회

- frontend/js/review.js
스포일러 더보기 처리
- 스포일러 none, block 처리
- 더보기 버튼
> [update] 스포일러 더보기 처리

- backend/build.gradle
- backend/src/main/java/site/bookmore/bookmore/books/entity/Book.java
- backend/src/main/java/site/bookmore/bookmore/books/service/BookService.java
- backend/src/main/java/site/bookmore/bookmore/books/util/api/naver/NaverBookCrawler.java
- backend/src/main/java/site/bookmore/bookmore/books/util/api/naver/NaverBooksearch.java
> [Feat] 크롤링 추가

- backend/src/main/java/site/bookmore/bookmore/alarms/dto/AlarmResponse.java
- backend/src/main/java/site/bookmore/bookmore/alarms/service/AlarmService.java
- backend/src/test/java/site/bookmore/bookmore/alarms/controller/AlarmControllerTest.java
프런트엔드 스크립트 작성 편의를 위해 ```AlarmResponse```를 수정했습니다.
```json
"content": [
{
"id": 4,
"alarmType": "NEW_FOLLOW",
"targetUserId": 2,
"fromUser": "1번 사용자",
"createdDatetime": "2023-02-07 16:36:53"
},
{
"id": 3,
"alarmType": "NEW_LIKE_ON_REVIEW",
"targetUserId": 2,
"fromUser": "1번 사용자",
"source": {
"title": "정의란 무엇인가 (대한민국의 정의에 대해 다시 생각해보는 세계적 베스트셀러)",
"reviewId": 1
},
"createdDatetime": "2023-02-07 16:36:47"
},
{
"id": 2,
"alarmType": "NEW_FOLLOW_REVIEW",
"targetUserId": 2,
"fromUser": "1번 사용자",
"source": {
"title": "정의란 무엇인가 (대한민국의 정의에 대해 다시 생각해보는 세계적 베스트셀러)",
"reviewId": 2
},
"createdDatetime": "2023-02-07 16:36:44"
}
]
```
> AlarmResponse 수정

- backend/src/main/java/site/bookmore/bookmore/reviews/dto/ReviewPageResponse.java
- backend/src/main/java/site/bookmore/bookmore/users/controller/FollowController.java
- backend/src/main/java/site/bookmore/bookmore/users/dto/FollowerResponse.java
- backend/src/main/java/site/bookmore/bookmore/users/dto/FollowingResponse.java
- backend/src/main/java/site/bookmore/bookmore/users/dto/UserDetailResponse.java
- backend/src/main/java/site/bookmore/bookmore/users/dto/UserPersonalResponse.java
- backend/src/main/java/site/bookmore/bookmore/users/service/FollowService.java
- backend/src/main/java/site/bookmore/bookmore/users/service/UserService.java
- 팔로우/팔로잉/유저 조회 수정
- 팔로우/팔로잉 조회시 프로필도 같이 나오게 수정
- 유저 상세 조회 시 id, 프로필이 나오도록 수정
- 유저 리뷰 조회 시 책 이름, isbn 나오도록 수정
- 팔로우 중인지 확인하는 API 추가
> 팔로우/팔로잉/유저 조회 수정

- frontend/css/font.css
- frontend/js/myfeed.js
- frontend/users/detail.html
> 마이피드 기능 구현

- frontend/js/ranks.js
- frontend/ranks.html
ranks 스크립트 구현
- 두 번째 ranks.html, ranks.js commit에 my 랭크가 추가되었습니다
> ranks 스크립트 구현

- backend/src/main/java/site/bookmore/bookmore/alarms/dto/AlarmResponse.java
- backend/src/test/java/site/bookmore/bookmore/alarms/controller/AlarmControllerTest.java
- frontend/index.html
- frontend/js/notifications.js
front: 팔로우 알림 클릭 시, 팔로우한 사람의 마이피드로 가도록 수정
back: dto 수정
- dto 수정: fromUserId가 필요하여 받아오도록 수정했습니다.
- back 수정이 간단하여 한 브랜치에서 back & front 모두 작업했습니다. (🙏🏻)
> 알림 dto & js 스크립트 수정

- backend/src/main/java/site/bookmore/bookmore/reviews/dto/ReviewPageResponse.java
- ReviewPageResponse에 유저 id 추가
- ReviewPageResponse에 userId를 추가
> ReviewPageResponse에 유저 id 추가

- frontend/js/login.js
- frontend/js/review.js
더보기, 숨기기 버튼 오작동 수정 https://github.com/likelion-backend-2nd-project-team11/book-more/issues/189
태그 파싱 버그 수정 https://github.com/likelion-backend-2nd-project-team11/book-more/issues/190
> 스포일러 더보기, 숨기기 버튼 오동작, 태그 파싱 로직 수정

- frontend/js/ranks.js
- frontend/ranks.html
랭킹 js 스크립트 수정
- 닉네임 클릭시 마이피드로 이동
- 랭킹 00시 업데이트 안내문구 추가
- commit 내용을 보니 html에서 띄어쓰기 부분들이 제거되어 있습니다.
> 랭킹 js 스크립트 수정

- frontend/js/mypage.js
비밀번호 를 넣지 않으면 null 값이 아닌 ("")값이 들어가서 오류가 생겼습니다.
- 값이 들어가지 않는다면 null로 변환 시켰습니다.
> [bug] 비밀번호 이슈

- frontend/js/mypage.js
- frontend/users/mypage.html
프로필 수정
- Edit 버튼 눌렀을 때 프로필 변경 모달 창 구현
> [update] 프로필 수정

- frontend/js/birth.js
- frontend/js/join.js
- frontend/users/join.html
회원가입 페이지 생일 셀렉트로 변경
- 머지 후 마이페이지 수정 모달에서도 생일 입력을 셀렉트로 변경해야합니다.
> 회원가입 페이지 생일 셀렉트로 변경

- frontend/js/myfeed.js
- myfeed.js에 alert 메세지 수정
- 피드에서 로그인하지 않은 상태로 팔로우 버튼을 누르면 팝업창 두 번 뜨는 문제 해결
> myfeed.js에 alert 메세지 수정

- backend/src/main/java/site/bookmore/bookmore/users/dto/FollowerResponse.java
- backend/src/main/java/site/bookmore/bookmore/users/dto/FollowingResponse.java
- backend/src/test/java/site/bookmore/bookmore/users/controller/FollowControllerTest.java
- backend/src/test/java/site/bookmore/bookmore/users/controller/UserControllerTest.java
- backend/src/test/java/site/bookmore/bookmore/users/service/FollowServiceTest.java
- backend/src/test/java/site/bookmore/bookmore/users/service/UserServiceTest.java
- 테스트 코드 작성 및 불필요한 변수 삭제
- 팔로우 기능 추가한 것들 테스트 코드 작성
- 유저 상세 조회 테스트 코드 작성
- FollowerResponse/FollowingResponse에 불필요한 변수 삭제
> 테스트 코드 작성 및 불필요한 변수 삭제

- frontend/js/mypage.js
- frontend/js/notifications.js
- frontend/users/join.html
회원 탈퇴 시, 확인 팝업 필요, placeholder 변경
-  placeholder 변경
- 회원 탈퇴 시, 확인 팝업 생성
- notifications에 confirm 메서드가 있어서  window.confirm이 동작을 안 해서
- confirm을 confirmNotification으로 수정했습니다.
> 회원 탈퇴 시, 확인 팝업 필요, placeholder 변경

- backend/src/main/java/site/bookmore/bookmore/common/exception/ErrorCode.java
- backend/src/main/java/site/bookmore/bookmore/common/exception/unauthorized/InvalidFileFormatException.java
- backend/src/main/java/site/bookmore/bookmore/s3/AwsS3Uploader.java
- frontend/js/mypage.js
- frontend/users/mypage.html
프로필 사진 변경 시
1. 이미지 파일만 업로드 가능하도록 수정
2. 미리보기 사이즈 조절
- 파일 선택 시 선택할 수 있는 파일 제한
- 그럼에도 사용자가 모든 파일 중 선택한다면 경고 문구 알림
- 그럼에도 업로드 시도하면 백엔드에서 예외 발생
- 미리보기 사이즈는 450*450으로 설정하였습니다.
> 프로필 사진 변경 기능 Fix

- frontend/js/mypage.js
- frontend/users/mypage.html
myPage 비밀번호 확인 추가
- myPage 비밀번호 확인 추가
> myPage 비밀번호 확인 추가

- backend/src/main/java/site/bookmore/bookmore/users/service/UserService.java
- frontend/js/mypage.js
1. mypage.js - 버튼 및 메서드 추가
2. UserService - updateProfile 메서드 조건 추가
- ```X``` 버튼을 누르면 기본 프로필로 변경할 것인지 묻고 기본 프로필로 변경해줍니다. (동시에 S3 bucket에 업로드된 사진 삭제)
- 이미 기본 프로필인 경우는 에러 메시지를 던져줍니다.
- 기본 프로필이 아닌 상태에서 프로필을 변경할 시, 기존의 프로필을 S3 bucket에서 삭제하고 새로운 파일을 업로드하도록 로직을 추가하였습니다.
> 프로필 사진 변경 기능 수정

- backend/src/main/java/site/bookmore/bookmore/books/controller/BookController.java
- backend/src/main/java/site/bookmore/bookmore/challenge/controller/ChallengeController.java
- backend/src/main/java/site/bookmore/bookmore/challenge/dto/ChallengeRequest.java
- backend/src/main/java/site/bookmore/bookmore/challenge/entity/Challenge.java
- backend/src/main/java/site/bookmore/bookmore/reviews/controller/ReviewController.java
- backend/src/main/java/site/bookmore/bookmore/reviews/dto/ReviewRequest.java
- backend/src/main/java/site/bookmore/bookmore/reviews/entity/Review.java
- backend/src/main/java/site/bookmore/bookmore/users/controller/UserController.java
- backend/src/main/java/site/bookmore/bookmore/users/dto/UserJoinRequest.java
- backend/src/main/java/site/bookmore/bookmore/users/dto/UserUpdateRequest.java
- backend/src/test/java/site/bookmore/bookmore/books/service/BookServiceTest.java
- backend/src/test/java/site/bookmore/bookmore/challenge/controller/ChallengeControllerTest.java
- frontend/js/review.js
컬럼 길이 수정 및 Validator 추가
- 챌린지
- 제목 : 50
- 본문 300
- 리뷰
- 본문 : 300
- 유저
- 닉네임 : 15
> 컬럼 길이 수정 및 Validator 추가

- frontend/books/detail.html
리뷰 수정 이슈 해결
- 300자 넘어가면  알림 발생
> [Feat] 리뷰 수정 이슈 해결

- frontend/challenge/index.html
챌린지 내용 제한
- challenge 내용 제한 300자 카운팅 추가
> [fix] challenge 내용 제한 300자 카운팅 추가
